### ISSUE TITLE
Potentially moving Kotlin specific DSL from ShadowMC to Forgelin

### ISSUE THREAD

**Issue by NicholasFeldman** [shadowfacts/Forgelin#10]
I believe at some point in the past you decided to merge ShadowMC with Forgelin, and created a bunch of DSL and extension functions there.

I was wondering about the possibility of moving these into Forgelin, so other mods can take advantage of this as well.

**Comment by shadowfacts** [comment]
Probably not. The extensions were originally moved to ShadowMC from Forgelin because I was the only person using them and it allows me to iterate faster.

Additionally, the UI DSL can't move to Forgelin as otherwise it would depend on ShadowMC.
