### ISSUE TITLE
kotlin-stdlib-jre8?

### ISSUE THREAD

**Issue by 3TUSK** [shadowfacts/Forgelin#11]
Now that `coroutine-jre8` is [included][build-gradle], why not include the [standard lib for jre8][stdlib-jre8-citation]?

I can imagine that doing so will lead to more complex issues (e.g. separate builds), but this can also provide those java 8 features to kotlin. So please consider about this.

> Or wait for Minecraft 1.12 Release?

[build-gradle]: https://github.com/shadowfacts/Forgelin/blob/master/build.gradle#L92
[stdlib-jre8-citation]: https://kotlinlang.org/docs/reference/whatsnew11.html#java-8-standard-library-support

**Comment by shadowfacts** [comment]
Whoops, forgot to add that one. I'll release an new version with it soon.

**Comment by Dawars** [comment]
When?
