### ISSUE TITLE
Coroutines library can't be resolved (without extra effort)

### ISSUE THREAD

**Issue by marvin-roesch** [shadowfacts/Forgelin#14]
I tried switching from my own Kotlin shading setup to using Forgelin, but unfortunately it wasn't as seemless as I had hoped. Builds were failing due to the coroutines library not being resolvable and it turns out that they're not on Maven Central ~~or JCenter. I had to add "https://dl.bintray.com/kotlin/kotlinx/" repository myself. Would be great if this was mentioned in the readme!~~ Turns out it is on JCenter, its search is just somewhat terrible. Would still be great if this was mentioned, considering not everybody has JCenter enabled by default!

**Comment by shadowfacts** [comment]
Coroutines are in JCenter (https://github.com/kotlin/kotlinx.coroutines#gradle), you should be able to access them just fine.

**Comment by marvin-roesch** [comment]
I was a little confused because I couldn't find the library for some reason. However, not everybody necessarily has the JCenter repo listed by default, so a note about it in the readme would be appreciated.
