### ISSUE TITLE
Repository down?

### ISSUE THREAD

**Issue by Dawars** [shadowfacts/Forgelin#17]
This page doesn't load for me where I am supposed to check the latest version: http://mvn.rx14.co.uk/shadowfacts/net/shadowfacts/Forgelin/

And so IntelliJ cannot download the dependency either

**Comment by Moritz30** [comment]
Same problem here

**Comment by shadowfacts** [comment]
Yes, RX14’s maven is down, there’s nothing I can do about it.

**Comment by Moritz30** [comment]
@shadowfacts

My developer team will shortly offer free maven repos for Minecraft mods. I think if you want to we could bring one up for you today. Do you have discord, skype or so so we can check the details?

**Comment by Moritz30** [comment]
Or you can also DM me on twitter: https://twitter.com/Moritz30MC

**Comment by shadowfacts** [comment]
Thanks, but I'll probably stick to RX14's Maven. If I do move, it would be to my own server.

**Comment by shadowfacts** [comment]
New Maven repository URL: [`http://maven.shadowfacts.net/`](http://maven.shadowfacts.net/)
