### ISSUE TITLE
world tick loop

### ISSUE THREAD

**Issue by cameronmyer0** [shadowfacts/Forgelin#18]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-101.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  CreativePatchingLoader (CreativeCore v1.7.6 mc1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  Land Craft (landcraft-2.2.0.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.1.1-64.jar)
  AstralCore (astralsorcery-1.12-1.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  LucraftForgeLoading (LucraftCore-1.12-1.2.1.jar)
  HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/16/17 4:15 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at nex.handler.EventHandler.onWorldTick(EventHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:746)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Mac OS X (x86_64) version 10.12.5
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1323820768 bytes (1262 MB) / 4674154496 bytes (4457 MB) up to 8234270720 bytes (7852 MB)
	JVM Flags: 25 total; -Xmx7936m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 2, allocated: 3, tallocated: 102
	FML: MCP 9.40 Powered by Forge 14.21.1.2413 Optifine OptiFine_1.12_HD_U_C4 163 mods loaded, 163 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2413.jar) 
	UCHIJAAAA	forge{14.21.1.2413} [Minecraft Forge] (forge-1.12-14.21.1.2413.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.12 - 3.1.9.jar) 
	UCHIJAAAA	msutilities{1.2.1} [MS Utilities] ([1.12] MS Utilities-1.2.1.jar) 
	UCHIJAAAA	gobblecore{1.12-0.1.5.23} [Gobble Core] (GobbleCore-1.12-0.1.5.23.jar) 
	UCHIJAAAA	charcoalblock{1.1} [A Block of Charcoal] (A Block of Charcoal-1.1.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r115} [Actually Additions] (ActuallyAdditions-1.12-r115.jar) 
	UCHIJAAAA	antigrav{1.0.4} [2kai2kai2's Anti-Gravity Mod] (AntiGrav-v.1.0.4-mc1.12.jar) 
	UCHIJAAAA	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHIJAAAA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAA	thedragonlib{1.12-4.1.0} [TheDragonLib] (thedragonlib-1.12-4.1.0.jar) 
	UCHIJAAAA	armorplus{1.12-11.3.4.11-alpha} [ArmorPlus] (armorplus-1.12-11.3.4.11-alpha.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCHIJAAAA	aromabackup{2.1.0.0.b71} [AromaBackup] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	aromabackuprecovery{2.1.0.0.b71} [AromaBackuprecovery] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	astralsorcery{1.6} [Astral Sorcery] (astralsorcery-1.12-1.6.jar) 
	UCHIJAAAA	psi{r1.1-52} [Psi] (Psi-r1.1-52.jar) 
	UCHIJAAAA	quark{r1.2-101} [Quark] (Quark-r1.2-101.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHIJAAAA	hammercore{1.9.3.6} [Hammer Core] (HammerCore-1.12-1.9.3.6.jar) 
	UCHIJAAAA	blackholestorage{17r} [Black Hole Storage] (BlackHoleStorage-1.12-17r.jar) 
	UCHIJAAAA	blockdrops{1.3.0} [Block Drops] (blockdrops-1.12-1.3.0.jar) 
	UCHIJAAAA	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHIJAAAA	bouncing_balls{1.5.1} [Bouncing Balls] (BouncingBalls-1.12-1.5.1.jar) 
	UCHIJAAAA	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	brandonscore{2.3.0} [Brandon's Core] (BrandonsCore-1.12-2.3.0.119-universal.jar) 
	UCHIJAAAA	campfire{1.1} [Simple Camp Fire] (campfire-1.12-v1.1.jar) 
	UCHIJAAAA	cavern{1.9.2} [Cavern] (Cavern_1.12-v1.9.2.jar) 
	UCHIJAAAA	ceramics{1.12-1.3.1} [Ceramics] (Ceramics-1.12-1.3.1.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chancecubes{1.12-3.0.1.199} [Chance Cubes] (ChanceCubes-1.12-3.0.1.199.jar) 
	UCHIJAAAA	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	claybucket{1.0} [Clay Bucket] (ClayBucket-1.12-1.0.jar) 
	UCHIJAAAA	cofhcore{4.3.2} [CoFH Core] (CoFHCore-1.12-4.3.2.7-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHIJAAAA	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCHIJAAAA	ic2{2.8.7-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.7-ex112.jar) 
	UCHIJAAAA	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.12-1.3.3.jar) 
	UCHIJAAAA	craftablesaddles{1.3} [Craftable Saddles] (Craftable Saddles[1.12]-1.3.jar) 
	UCHIJAAAA	craftingtweaks{8.1.1} [Crafting Tweaks] (CraftingTweaks_1.12-8.1.1.jar) 
	UCHIJAAAA	crafttweaker{3.0.26} [CraftTweaker2] (CraftTweaker2-1.12-4.0.0.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.0.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.6 mc1.12.jar) 
	UCHIJAAAA	creativeplus{1.0.1} [Creative+] (CreativePlus MC1.12 v1.0.1.jar) 
	UCHIJAAAA	creeperconfetti{1.4.1} [Creeper Confetti] (creeperconfetti-1.4.1.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	custommainmenu{2.0.6} [Custom Main Menu] (CustomMainMenu-MC1.12-2.0.6.jar) 
	UCHIJAAAA	cxlibrary{1.5.1} [CXLibrary] (cxlibrary-1.12-1.5.1.jar) 
	UCHIJAAAA	darkutils{1.6.158} [Dark Utilities] (DarkUtils-1.12-1.6.158.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJAAAA	draconicevolution{2.3.0} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.0.254-universal.jar) 
	UCHIJAAAA	durabilityshow{5.0.0} [Durability Show] (Durability Show-1.12-5.0.0.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	endadvance{1.12-2.0.0.0} [Ender Advancement] (endadvance-1.12-2.0.0.0.jar) 
	UCHIJAAAA	shetiphiancore{3.5.0.2} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.2.jar) 
	UCHIJAAAA	endertanks{1.6.0.2} [EnderTanks] (endertanks-1.12.0-1.6.0.2.jar) 
	UCHIJAAAA	energyconverters{1.0.0.1} [Energy Converters] (energyconverters_1.12-1.0.0.1.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHIJAAAA	goodluckskeleton{1.0} [Good Luck Skeleton] (goodluckskeleton-1.1-MC1.12.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	harvest{1.12-1.2.3-15} [Harvest] (Harvest-1.12-1.2.3-15.jar) 
	UCHIJAAAA	igcm{1.0.0} [InGameConfigManager] (IGCM v1.2.0 pre-1 mc1.12.jar) 
	UCHIJAAAA	theoneprobe{1.4.13} [The One Probe] (theoneprobe-1.12-1.4.13.jar) 
	UCHIJAAAA	immersiveengineering{0.12-66} [Immersive Engineering] (ImmersiveEngineering-0.12-66.jar) 
	UCHIJAAAA	immersivepetroleum{1.0.10} [Immersive Petroleum] (immersivepetroleum-1.12-1.0.10.jar) 
	UCHIJAAAA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJAAAA	integrateddynamics{0.7.6} [Integrated Dynamics] (IntegratedDynamics-1.12-0.7.6.jar) 
	UCHIJAAAA	integrateddynamicscompat{1.0.0} [IntegratedDynamics-Compat] (IntegratedDynamics-1.12-0.7.6.jar) 
	UCHIJAAAA	integratedtunnels{1.2.4} [Integrated Tunnels] (IntegratedTunnels-1.12-1.2.4.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	jaff{1.7_for_1.12} [Just a Few Fish] (JustAFewFish-1.7_for_1.12.jar) 
	UCHIJAAAA	justenoughbuttons{1.12-1.2.1} [Just Enough Buttons] (justenoughbuttons-1.12-1.2.1.jar) 
	UCHIJAAAA	jeresources{0.8.1.14} [Just Enough Resources] (JustEnoughResources-1.12-0.8.1.14.jar) 
	UCHIJAAAA	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCHIJAAAA	landcore{1.5.0.0} [LandCore] (landcore-1.5.0.0.jar) 
	UCHIJAAAA	landcraft{2.2.0.0} [Land Craft] (landcraft-2.2.0.0.jar) 
	UCHIJAAAA	lucraftcore{1.12-1.2.1} [Lucraft: Core] (LucraftCore-1.12-1.2.1.jar) 
	UCHIJAAAA	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCHIJAAAA	morefurnaces{1.10.1} [More Furnaces] (MoreFurnaces-1.12-1.10.1.jar) 
	UCHIJAAAA	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCHIJAAAA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJAAAA	mputils{1.4.1} [MPUtils] (MPUtils-1.12-1.4.1.jar) 
	UCHIJAAAA	mpbasic{1.3.0} [ModPack Basic Tools] (mpbasic-1.12-1.3.0.jar) 
	UCHIJAAAA	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UCHIJAAAA	multistorage{1.4.0.2} [Multi-Storage] (multistorage-1.12.0-1.4.0.2.jar) 
	UCHIJAAAA	mycommands{1.12-02} [MY Commands] (MyCommands-1.12-02.jar) 
	UCHIJAAAA	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1a.jar) 
	UCHIJAAAA	mysticalagradditions{1.2.0} [Mystical Agradditions] (mysticalagradditions[1.12]-1.2.0.jar) 
	UCHIJAAAA	naturescompass{1.4.0} [Nature's Compass] (NaturesCompass-1.12-1.4.0.jar) 
	UCHIJAAAA	netherchest{0.2.1} [Nether Chest] (netherchest-0.2.1.jar) 
	UCHIJAAAA	nex{2.1.5.6} [NetherEx] (NetherEx-1.12-2.1.5.6.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCHIJAAAA	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCHIJAAAA	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	UCHIJAAAA	overloaded{0.0.26} [Overloaded] (Overloaded-1.12-0.0.26.jar) 
	UCHIJAAAA	placementpreview{0.3.1} [Placement Preview] (placementpreview-1.12.0-0.3.1.jar) 
	UCHIJAAAA	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHIJAAAA	reborncore{3.2.4.86} [Reborn Core] (RebornCore-1.12-3.2.4.86-universal.jar) 
	UCHIJAAAA	quantumstorage{4.3.5} [QuantumStorage] (QuantumStorage-1.12-4.3.5.jar) 
	UCHIJAAAA	quickhotbar{1.05} [Quick Hotbar] (quickhotbar_112_1.05.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
	UCHIJAAAA	sandro{1.2a} [Sandro's Core] (Redstone++ ver1.2a.jar) 
	UCHIJAAAA	redstoneplusplus{1.2a} [Redstone++] (Redstone++ ver1.2a.jar) 
	UCHIJAAAA	thermalfoundation{2.3.2} [Thermal Foundation] (ThermalFoundation-1.12-2.3.2.8-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.2} [Thermal Expansion] (ThermalExpansion-1.12-5.3.2.10-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.3.2} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.2.6-universal.jar) 
	UCHIJAAAA	refinedstorage{1.5.11} [Refined Storage] (refinedstorage-1.5.11.jar) 
	UCHIJAAAA	reptilemod{3.8.0} [Reptile Mod] (reptilemod-1.12-3.8.0-70.jar) 
	UCHIJAAAA	roguelike{1.7.0} [Roguelike Dungeons] (RoguelikeDungeons-1.12-1.7.0.jar) 
	UCHIJAAAA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJAAAA	rustic{0.3.10} [Rustic] (rustic-0.3.10.jar) 
	UCHIJAAAA	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCHIJAAAA	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCHIJAAAA	scalinghealth{1.1.1} [Scaling Health] (ScalingHealth-1.12-1.1.1-64.jar) 
	UCHIJAAAA	silentgems{2.4.2} [Silent's Gems] (SilentsGems-1.12-2.4.2-206.jar) 
	UCHIJAAAA	sgextraparts{1.3.1} [Silent's Gems: Extra Parts] (SGExtraParts-1.12-1.3.1-25.jar) 
	UCHIJAAAA	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCHIJAAAA	shulkerbox{1.2.1} [Shulkerbox] (shulkerbox-1.2.1.jar) 
	UCHIJAAAA	simplequarry{1.0.7} [Simple Quarry] (SimpleQuarry-1.12-1.0.7.jar) 
	UCHIJAAAA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCHIJAAAA	yukarilib{1.3.0} [YukariLib] (YukariLib-1.12-1.3.0.jar) 
	UCHIJAAAA	solidxp{1.4.0-beta} [SolidXp] (SolidXp-1.4.0-b2.jar) 
	UCHIJAAAA	sparkshammers{1.6.6.2} [Spark's Hammers] (sparkshammers-1.12-1.6.6.2.jar) 
	UCHIJAAAA	speedsterheroes{1.12-1.2.1} [SpeedsterHeroes] (SpeedsterHeroes-1.12-1.2.1.jar) 
	UCHIJAAAA	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UCHIJAAAA	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.2} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.2.9-universal.jar) 
	UCHIJAAAA	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCHIJAAAA	topaddons{1.12-0.15.0} [TOP Addons] (topaddons-1.12-0.15.0.jar) 
	UCHIJAAAA	torchmaster{1.4.3.8} [TorchMaster] (torchmaster_1.12-1.4.3.8.jar) 
	UCHIJAAAA	toroquest{1.11.2-5.1} [ToroQuest] (toroquest-1.12-5.1.jar) 
	UCHIJAAAA	unifieditems{1.6.4.187} [Unified Items] (UnifiedItems-1.12-1.6.4-187.jar) 
	UCHIJAAAA	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCHIJAAAA	vefluids{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [VoltzEngine Fluids module] (VE-FluidHandling-1.12-0.8.0b3.jar) 
	UCHIJAAAA	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCHIJAAAA	vrgenerator{5.0.1} [VisibleRayGenerator] (VisibleRayGenerator-1.12-5.0.1-universal.jar) 
	UCHIJAAAA	wearablebackpacks{3.0.3} [Wearable Backpacks] (WearableBackpacks-1.12-3.0.3.jar) 
	UCHIJAAAA	woodenbucket{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Bucket] (WoodenBuckets-1.12-0.2.0b9.jar) 
	UCHIJAAAA	yabba{1.12-0.5.3} [YABBA] (YABBA-1.12-0.5.3.jar) 
	UCHIJAAAA	yeoldetanks{2.1.0} [Ye Olde Tanks] (YeOldeTanks-1.12-2.1.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-101.jar)
  vazkii.quark.base.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  cubex2.cxlibrary.CoreModTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
CreativePatchingLoader (CreativeCore v1.7.6 mc1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
Land Craft (landcraft-2.2.0.0.jar)
  landmaster.landcraft.asm.Transform
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  shetiphian.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
SHLoadingPlugin (ScalingHealth-1.12-1.1.1-64.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
AstralCore (astralsorcery-1.12-1.6.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
LucraftForgeLoading (LucraftCore-1.12-1.2.1.jar)
  lucraft.mods.lucraftcore.access.LucraftClassTransformer
HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.4.86
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['camoman32'/952, l='testing', x=11.00, y=65.00, z=234.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-10.2.36
	OpenGlRenderer: ATI Radeon HD 4670 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by yrsegal** [comment]
why... why is this reported to forgelin? It's a crash in NetherEx...

**Comment by cameronmyer0** [comment]
Because I didn't know what it was for sorry for the inconvenience
