### ISSUE TITLE
Forgelin.kt version

### ISSUE THREAD

**Issue by dmodoomsirius** [shadowfacts/Forgelin#19]
https://github.com/shadowfacts/Forgelin/blob/master/src/main/kotlin/net/shadowfacts/forgelin/Forgelin.kt#L13

the version inside that class file does not match the jar name. which is causing mods that require forgelin 1.5.0 to think its not found.

I think you can use gradle or even forge gradle to replace that version for you.

Edit. Looks like ForgeGradle can't replace easily when its a build.gradle.

**Comment by shadowfacts** [comment]
Forgelin 1.5.1 has been released, fixing this.

**Comment by dmodoomsirius** [comment]
thank you very much :D
