### ISSUE TITLE
maybe it's time for a new version?

### ISSUE THREAD

**Issue by faceofcat** [shadowfacts/Forgelin#25]
Kotlin 1.1.50 is out!

https://blog.jetbrains.com/kotlin/2017/09/kotlin-1-1-50-is-out/

**Comment by AlexCouch** [comment]
Is this why forgelin isn't doing anything in my project? Or would that be a separate issue?

**Comment by Bluexin** [comment]
Separate issue

**Comment by RebelliousUno** [comment]
https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-1-60-is-out/ 1.1.60 now (will see about updating the PR when I get 5 mins)

**Comment by Bluexin** [comment]
1.2 is now out (I knew it was coming anytime now xD)
@shadowfacts are you still interested in updating this project or should someone fork it?

EDIT: he replied to me on discord saying he'll update soon ;p

**Comment by shadowfacts** [comment]
Forgelin 1.6.0 has been released with Kotlin 1.2.0.

**Comment by RebelliousUno** [comment]
Thank you:)
