### ISSUE TITLE
Forgelin Not Loading My Kotlin Project Into Forge

### ISSUE THREAD

**Issue by AlexCouch** [shadowfacts/Forgelin#26]
Literally nothing is happening. I have a kotlin project set up with my main mod class/object annotated with mod and I put the KotlinAdapter into the annotation paramter "modLanguageAdapter" but it doesn't seem to be doing anything. There's nothing in the console about it. It's just not loading. Minecraft loads up just fine. The mods list doesn't show my project either. I'm using 1.12.2 with Forgelin 1.5.1. My repo is here: https://github.com/AlexCouch/quester/tree/kotlin-refactor

**Comment by faceofcat** [comment]
maybe your mod class should not be in 'test' ?

![image](https://user-images.githubusercontent.com/23014228/31327929-e9318864-acda-11e7-8d06-a11278e05e46.png)

**Comment by faceofcat** [comment]
also... you probably want the kotlin-gradle plugin too:

```
buildscript {
    ext.kotlin_version = project.kotlin_version
    repositories {
        mavenCentral()
        [...]
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${project.kotlin_version}"
    }
}
apply plugin: "net.minecraftforge.gradle.forge"
apply plugin: 'kotlin'
```

where, for latest forgelin, I think this is correct:
```
kotlin_version = 1.1.3-2
```

**Comment by AlexCouch** [comment]
Interesting...I've never used a test module before so I just assumed it was for organizational purposes so I just used it. I'll change it to my regular module. Thanks!
