### ISSUE TITLE
Mod not marked as supporting 1.12.2 

### ISSUE THREAD

**Issue by C0rn3j** [shadowfacts/Forgelin#27]
Hi, this mod is not marked as 1.12.2 yet some mods released for it rely on it, so I assume it works as it should.

https://minecraft.curseforge.com/projects/shadowfacts-forgelin/files

please mark the 1.12 file as 1.12.2 too. (mod relying on it - Armorplus for example)

This "broke" my updater script.

**Comment by sandalle** [comment]
Seems to work on my Minecraft 1.12.2 [modpack](https://minecraft.curseforge.com/projects/nst-world-of-color), which isn't released yet pending mods marking 1.12.2 compatibility such as this. ;)

**Comment by shadowfacts** [comment]
Fixed.
