### ISSUE TITLE
[1.12.2] Crash with v1.6.0 Forge 2582

### ISSUE THREAD

**Issue by MokahTGS** [shadowfacts/Forgelin#29]
Getting a crash with v 1.6.0 and forge 2582

https://pastebin.com/2xqM77vA

**Comment by faceofcat** [comment]
probably about this:

https://github.com/shadowfacts/ShadowMC/blob/1.12.2/src/main/java/net/shadowfacts/shadowmc/network/PacketBase.java#L43

not really related to forgelin.
