### ISSUE TITLE
Unnecessary dependency: kotlin-runtime

### ISSUE THREAD

**Issue by mainrs** [shadowfacts/Forgelin#30]
Looks like the newer versions of kotlin just need to bundle the `kotlin-stdlib` with them. At least that's what google spit out after doing some research.

**Comment by shadowfacts** [comment]
Do you have an official source for this? I haven't seen/heard anything about it?

**Comment by mainrs** [comment]
https://discuss.kotlinlang.org/t/runtime-included-in-stdlib/2421
One of the jetbrains members has posted in this thread telling that the runtime is, as of 1.1, included in the standard library.

**Comment by shadowfacts** [comment]
Fixed in 1.7.0
