### ISSUE TITLE
[question/gradle] Execution failed for task ':compileKotlin'.

### ISSUE THREAD

**Issue by Frontrider** [shadowfacts/Forgelin#31]
The issue is definietly with me, but based on the examples I could find I have no idea why the build fails.

[build.gradle.txt](https://github.com/shadowfacts/Forgelin/files/1821614/build.gradle.txt)
[gradle.properties.txt](https://github.com/shadowfacts/Forgelin/files/1821615/gradle.properties.txt)
Fails with:
e: java.io.FileNotFoundException: C:\Users\Jump\IdeaProjects\modern_computers\build\kotlin-classes\main\META-INF\"modern_computers".kotlin_module 

So, the cause is that it just does not compiles kotlin sources.

**Comment by yrsegal** [comment]
you're putting a " in your filename. no. bad.

**Comment by Frontrider** [comment]
Yeah, shortly after that I figure it out, that I had the quotation marks in my config file.
