### ISSUE TITLE
[1.12.2] Crash On Start-Up 1.7

### ISSUE THREAD

**Issue by Draskh** [shadowfacts/Forgelin#37]
[crash-2018-06-09_22.41.54-client.txt](https://github.com/shadowfacts/Forgelin/files/2087314/crash-2018-06-09_22.41.54-client.txt)
[crash-2018-06-09_22.41.55-client.txt](https://github.com/shadowfacts/Forgelin/files/2087315/crash-2018-06-09_22.41.55-client.txt)

**Comment by Mongole** [comment]
I'm getting the same crash also
https://paste.ee/p/3DYWf
