### ISSUE TITLE
Lastest version crash [1.7.3]

### ISSUE THREAD

**Issue by TheCorinthians** [shadowfacts/Forgelin#42]
Here's the link to the crash report...
https://pastebin.com/QxqJpNsc
Now, I noticed that Ender Ore errored as well, but the crash is specifically reporting towards your mod, it seems like a mod conflict or something but, there it is...

**Comment by TheCorinthians** [comment]
I just downgraded to 1.7.2, still got a [crash](https://pastebin.com/LihaHMr8) but it did not conflict with the mod I mentioned above... I'm downgrading more until I give up and wait for you guys, lmao, take your time, too  :)

**Comment by TheSnowyChickens** [comment]
I have this crash too. :)

**Comment by TheCorinthians** [comment]
Ayye, thank God I'm not the only one, lmfao

**Comment by TheCorinthians** [comment]
Omg, I went to MC v1.11.2 and it still crashed...  :')  I'll just give up and wait...  :')

**Comment by Dragnier** [comment]
Same issue. Downgraded to previous version and loaded fine.
Crashlog: https://paste.dimdev.org/rasekoyuyu.mccrash

**Comment by Foxgreat** [comment]
according to file weight - something goes wrong while updating)

**Comment by kellixon** [comment]
Recently, constant crashes after the update (1.7.1, 1.7.3). Can be the first author to test, and then post updates?
crash-reports - https://pastebin.com/VzQt1neB

**Comment by Pythonic-Rainbow** [comment]
Bug confirmed. Tho why kotlin won't be compiled with gradle?
Downgrading to 1.7.2 solves the issue

**Comment by TheCorinthians** [comment]
Ok, 1.7.2 it is for now, thank you everyone for understanding the problem and commenting here, bless the fact that we're not alone here, you all are awesome :)♡

**Comment by Davoleo** [comment]
Experiencing the same issue

**Comment by MxtressMyxx** [comment]
Same with 1.7.3, gonna try 1.7.2, will report my findings

**Comment by Kuktar** [comment]
This is ruining alot of peoples day.... it crashes Minecraft no matter what
this newest version 1.7.3 should be taken of curse ASAP please.

**Comment by shadowfacts** [comment]
1.7.3 has been pulled from CF. Revert to 1.6.0.

**Comment by Kuktar** [comment]
Thank you fine sir. Let me buy you a steak. What's your donation method?

**Comment by kellixon** [comment]
Despite all the mistakes, thank you for what you do! 1.7.2 - fully working version.

**Comment by shadowfacts** [comment]
Fixed in 1.7.4 (https://minecraft.curseforge.com/projects/shadowfacts-forgelin/files/2573311).

**Comment by TheCorinthians** [comment]
THANK YOU, WE LOVE YOU, SHADOWFACTS!!

**Comment by Kuktar** [comment]
Yes we do love you
