### ISSUE TITLE
Kotlin 1.3 is out

### ISSUE THREAD

**Issue by dmarcuse** [shadowfacts/Forgelin#43]
[Kotlin 1.2.50 was released a few days ago](https://blog.jetbrains.com/kotlin/2018/06/kotlin-1-2-50-is-out/). It's mostly just changes to tooling, but there's a couple library changes as well.

**Comment by BloodWorkXGaming** [comment]
To update this, yesterday Kotlin 1.2.70 got released:
https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-2-70-is-out/

**Comment by dblsaiko** [comment]
https://blog.jetbrains.com/kotlin/2018/10/kotlin-1-3/
Now would really be the time to update this.

**Comment by shadowfacts** [comment]
Forgelin 1.8.0 includes Kotlin 1.3.0 and Coroutines 1.0.0.

It's available on Maven and currently pending approval on CF.

**Comment by BloodWorkXGaming** [comment]
Awesome! Thanks shadow!

Shadowfacts <notifications@github.com> schrieb am Mi., 31. Okt. 2018, 00:27:
