### ISSUE TITLE
Kotlin 1.3.10 Coroutines 1.0.1

### ISSUE THREAD

**Issue by NikkyAI** [shadowfacts/Forgelin#48]
I was gonna make a PR but there are some weird issues with gradle and idea that i do not have the time to solve,
so all i can leave is a request to release a update with the updated versions

**Comment by shadowfacts** [comment]
Forgelin 1.8.1 with Kotlin 1.3.10 and Coroutines 1.0.1 has been published to GitHub and Maven and is currently pending approval on CurseForge.

**Comment by NikkyAI** [comment]
the jar is `11.66 KB` big, it does not bundle the dependencies

**Comment by shadowfacts** [comment]
Ah crap. Fixed in 1.8.2 (now available on GH, Maven, and CF).
