### ISSUE TITLE
[1.12.2] crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [shadowfacts/Forgelin#49]
Hi,

with your newest version from today (Forgelin-1.8.1), MC crash during the start up.

crash log : https://paste.dimdev.org/qetuyidava.mccrash

MC: 1.12.2
Forgelin-1.8.1
Forge: 2775

**Comment by dungsil** [comment]
![Forgelin 1.8.1 unpack](https://github.com/ressedpanda-archive/github-static-files/raw/master/shadowfacts%24Forgelin/issues%2349/1543041536.png)
◁ 1.8.0 | 1.8.1 ▷

The Kotlin library is missing Forgelin1.8.1.

**Comment by Darkmega18** [comment]
I also have the same crash as snowychickens

**Comment by zefut** [comment]
French/français ---> Avez vous trouvés une solution a ce problème de crash ?

Inglish/anglais ---> Have you found a solution to this crash problem?

**Comment by brisingraerowing** [comment]
@zefut Downgrade to 1.8.0 until this is fixed.

**Comment by ScienceDrummer** [comment]
Same thing.

https://paste.dimdev.org/ahofobecax.mccrash

**Comment by shadowfacts** [comment]
Fixed in 1.8.2 (currently pending approval on CurseForge).
