### ISSUE TITLE
Forgelin lacks an @Mod so it can't be sorted as a dependancy

### ISSUE THREAD

**Issue by yrsegal** [shadowfacts/Forgelin#5]
This would allow much more informative error logs when trying to use the kotlin adapter, as right now it just has a generic ClassDefNotFound if Forgelin is missing, rather than having the standard dependency screen people are used to.

**Comment by shadowfacts** [comment]
I would change it, but there's some mod that shades Forgelin, and adding an @Mod class would then break when the mod that's shading it and Forgelin itself were in the same instance.

**Comment by yrsegal** [comment]
Maybe that'd be a good way to convince that person to not shade it. :P

**Comment by shadowfacts** [comment]
The only problem is, I don't remember who's doing the shading :P

**Comment by yrsegal** [comment]
I still say that someone else doing something wrong isn't a good reason to prevent yourself from doing something right

**Comment by Eladkay** [comment]
It's me and I'm not doing it

**Comment by shadowfacts** [comment]
Alright, I'll try to change it soon.

**Comment by shadowfacts** [comment]
1.3.0 now has an `@Mod` annotated object, and you should be able to use `required-after:forgelin;` in `@Mod.dependencies`. It's on my Maven repo and is currently pending approval on CurseForge.
