### ISSUE TITLE
Crash after updating Forgelin to latest version 1.3.0 (1.10.2)

### ISSUE THREAD

**Issue by ate0ate** [shadowfacts/Forgelin#6]
Shadowfacts Forgelin updated to 1.3.0, but after updating, LibrarianLib crashes Minecraft during startup. No crash report is generated by this crash so here is the relevant client log. Obviously only the last part is most likely relevant where it states that LibrarianLib cannot start because it needs Forgelin to run. Thanks!

http://pastebin.com/jHg35j0R

I posted this issue with yrsegal as well.

**Comment by shadowfacts** [comment]
@Eladkay @yrsegal ping

**Comment by yrsegal** [comment]
It's the same error as #7, it's just that we use the adapter

**Comment by shadowfacts** [comment]
Fixed in Forgelin 1.3.1 (~~currently pending approval on~~ [CurseForge](https://minecraft.curseforge.com/projects/shadowfacts-forgelin/files/2382547)).
